

-- (1) ESPECIFICACIÓN
CREATE OR REPLACE PACKAGE pkg_producto AS
  PROCEDURE LISTAR(
    P_CURSOR OUT SYS_REFCURSOR
  );

  PROCEDURE CREAR(
    P_NOMBRE       IN NVARCHAR2,
    P_CATEGORIA    IN NVARCHAR2,
    P_DESCRIPCION  IN NVARCHAR2,
    P_PRECIO       IN NUMBER,
    P_PRODUCTO_ID  OUT NUMBER
  );

  PROCEDURE ACTUALIZAR(
    P_PRODUCTO_ID  IN NUMBER,
    P_NOMBRE       IN NVARCHAR2,
    P_CATEGORIA    IN NVARCHAR2,
    P_DESCRIPCION  IN NVARCHAR2,
    P_PRECIO       IN NUMBER
  );

  PROCEDURE OBTENER_POR_ID(
    P_PRODUCTO_ID IN NUMBER,
    P_CURSOR      OUT SYS_REFCURSOR
  );

  PROCEDURE ELIMINAR(
    P_PRODUCTO_ID IN NUMBER
  );
END pkg_producto;
/

-- (2) BODY
CREATE OR REPLACE PACKAGE BODY pkg_producto AS

  PROCEDURE LISTAR(P_CURSOR OUT SYS_REFCURSOR) IS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT producto_id, nombre, categoria, descripcion, precio
      FROM producto
      ORDER BY producto_id DESC;
  END LISTAR;

  PROCEDURE CREAR(
    P_NOMBRE IN NVARCHAR2, P_CATEGORIA IN NVARCHAR2, P_DESCRIPCION IN NVARCHAR2,
    P_PRECIO IN NUMBER, P_PRODUCTO_ID OUT NUMBER
  ) IS
  BEGIN
    INSERT INTO producto(nombre, categoria, descripcion, precio)
    VALUES (P_NOMBRE, P_CATEGORIA, P_DESCRIPCION, P_PRECIO)
    RETURNING producto_id INTO P_PRODUCTO_ID;
  END CREAR;

  PROCEDURE ACTUALIZAR(
    P_PRODUCTO_ID IN NUMBER, P_NOMBRE IN NVARCHAR2, P_CATEGORIA IN NVARCHAR2,
    P_DESCRIPCION IN NVARCHAR2, P_PRECIO IN NUMBER
  ) IS
  BEGIN
    UPDATE producto
       SET nombre = P_NOMBRE,
           categoria = P_CATEGORIA,
           descripcion = P_DESCRIPCION,
           precio = P_PRECIO
     WHERE producto_id = P_PRODUCTO_ID;
  END ACTUALIZAR;

  PROCEDURE OBTENER_POR_ID(P_PRODUCTO_ID IN NUMBER, P_CURSOR OUT SYS_REFCURSOR) IS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT producto_id, nombre, categoria, descripcion, precio
        FROM producto
       WHERE producto_id = P_PRODUCTO_ID;
  END OBTENER_POR_ID;

  PROCEDURE ELIMINAR(P_PRODUCTO_ID IN NUMBER) IS
  BEGIN
    DELETE FROM producto WHERE producto_id = P_PRODUCTO_ID;
  END ELIMINAR;

END pkg_producto;







