--1
CREATE OR REPLACE TRIGGER TRG_DETALLEPEDIDO_AI_ACTUALIZA_INV
AFTER INSERT ON DETALLEPEDIDO
FOR EACH ROW
BEGIN
  UPDATE INVENTARIO
  SET CANTIDAD_ACTUAL = CANTIDAD_ACTUAL - :NEW.CANTIDAD
  WHERE PRODUCTO_ID = :NEW.PRODUCTO_ID;
END;
/

--2
CREATE OR REPLACE TRIGGER TRG_DETALLEORDEN_AI_ACTUALIZA_INV
AFTER INSERT ON DETALLEORDEN
FOR EACH ROW
BEGIN
  UPDATE INVENTARIO
  SET CANTIDAD_ACTUAL = CANTIDAD_ACTUAL + :NEW.CANTIDAD
  WHERE PRODUCTO_ID = :NEW.PRODUCTO_ID;
END;
/

--3

CREATE OR REPLACE TRIGGER TRG_RECLAMO_AI_CAMBIA_ESTADO_PEDIDO
AFTER INSERT ON RECLAMO
FOR EACH ROW
BEGIN
  UPDATE PEDIDO
  SET ESTADO = 'EN_RECLAMO'
  WHERE PEDIDO_ID = (
    SELECT DP.PEDIDO_ID
    FROM DETALLEPEDIDO DP
    WHERE DP.DETALLE_PEDIDO_ID = :NEW.DETALLE_PEDIDO_ID
  );
END;
/

--4

CREATE OR REPLACE TRIGGER TRG_DEVOLUCION_AI_REINGRESA_INV
AFTER INSERT ON DEVOLUCION
FOR EACH ROW
DECLARE
  v_producto_id  DETALLEPEDIDO.PRODUCTO_ID%TYPE;
  v_cantidad     DETALLEPEDIDO.CANTIDAD%TYPE;
BEGIN
  SELECT PRODUCTO_ID, CANTIDAD
  INTO v_producto_id, v_cantidad
  FROM DETALLEPEDIDO
  WHERE DETALLE_PEDIDO_ID = :NEW.DETALLE_PEDIDO_ID;

  UPDATE INVENTARIO
  SET CANTIDAD_ACTUAL = CANTIDAD_ACTUAL + v_cantidad
  WHERE PRODUCTO_ID = v_producto_id;
END;
/

--5

CREATE OR REPLACE TRIGGER TRG_USUARIO_BI_NORMALIZA
BEFORE INSERT ON USUARIO
FOR EACH ROW
BEGIN
  :NEW.NOMBRE_USUARIO := UPPER(:NEW.NOMBRE_USUARIO);
  :NEW.ROL := UPPER(:NEW.ROL);

  IF :NEW.ESTADO IS NULL THEN
    :NEW.ESTADO := 'ACTIVO';
  END IF;
END;
/

--6

CREATE OR REPLACE TRIGGER trg_reclamo_pedido_estado
AFTER INSERT ON reclamo
FOR EACH ROW
BEGIN
    UPDATE pedido
    SET estado = 'EN_RECLAMO'
    WHERE pedido_id = (
        SELECT a.pedido_id
        FROM atencioncliente a
        WHERE a.atencion_id = :NEW.atencion_id
    );
END;
/

--7
CREATE OR REPLACE TRIGGER trg_devolucion_pedido_estado
AFTER INSERT ON devolucion
FOR EACH ROW
BEGIN
    UPDATE pedido
    SET estado = 'DEVUELTO'
    WHERE pedido_id = (
        SELECT a.pedido_id
        FROM atencioncliente a
        JOIN reclamo r ON r.atencion_id = a.atencion_id
        WHERE r.reclamo_id = :NEW.reclamo_id
    );
END;
/




