---------------------- VERIFICACIÓN INICIAL ---------------------------------

SHOW CON_NAME;
SHOW USER;

ALTER SESSION SET CONTAINER = XEPDB1;

SELECT tablespace_name, file_name 
FROM dba_data_files
WHERE tablespace_name LIKE 'TS_PROYECTOSC504%';

---------------------------- DESARROLLO ------------------------------------

-- TABLESPACES 
CREATE TABLESPACE ts_proyectoSC504_app
    DATAFILE 'C:\APP\PC\PRODUCT\21C\ORADATA\XE\XEPDB1\ts_proyectoSC504_app.dbf' SIZE 50M
    AUTOEXTEND ON NEXT 10M MAXSIZE 500M;

CREATE TEMPORARY TABLESPACE ts_temp_proyectoSC504_app
  TEMPFILE 'C:\APP\PC\PRODUCT\21C\ORADATA\XE\XEPDB1\ts_temp_proyectoSC504_app.tmp'
  SIZE 50M AUTOEXTEND ON NEXT 10M MAXSIZE 500M;


-- USUARIO 
CREATE USER USR_PROYECTOSC504_APP IDENTIFIED BY "admin123"
  DEFAULT TABLESPACE ts_proyectoSC504_app
  TEMPORARY TABLESPACE ts_temp_proyectoSC504_app
  QUOTA UNLIMITED ON ts_proyectoSC504_app;


-- ROL 
CREATE ROLE ROL_PROYECTOSC504_APP;


-- PERMISOS PARA EL ROL
GRANT 
    CREATE SESSION,
    CREATE TABLE,
    CREATE VIEW,
    CREATE SEQUENCE,
    CREATE PROCEDURE,
    CREATE SYNONYM,
    ALTER SESSION,
    CREATE TRIGGER
TO ROL_PROYECTOSC504_APP;


-- ASIGNACIÓN DEL ROL AL USUARIO
GRANT ROL_PROYECTOSC504_APP TO USR_PROYECTOSC504_APP;

