--1)
--ABRE
CREATE OR REPLACE PROCEDURE T_ORDENES_POR_PROVEEDOR(
CSDATOS OUT SYS_REFCURSOR,
PPROVEEDOR_ID IN PROVEEDOR.PROVEEDOR_ID%TYPE
)
AS
BEGIN
   OPEN CSDATOS FOR
      SELECT O.ORDEN_COMPRA_ID,
             O.PROVEEDOR_ID,
             P.NOMBRE AS NOMBRE_PROVEEDOR,
             O.FECHA,
             O.ESTADO
      FROM ORDENCOMPRA O
      JOIN PROVEEDOR P ON P.PROVEEDOR_ID=O.PROVEEDOR_ID
      WHERE O.PROVEEDOR_ID=PPROVEEDOR_ID
      ORDER BY O.FECHA DESC;
END;
/


--LLAMA
CREATE OR REPLACE PROCEDURE CALL_T_ORDENES_POR_PROVEEDOR(
PPROVEEDOR_ID IN PROVEEDOR.PROVEEDOR_ID%TYPE
)
AS
   DATOS SYS_REFCURSOR;
   VORDEN ORDENCOMPRA.ORDEN_COMPRA_ID%TYPE;
   VPROV PROVEEDOR.PROVEEDOR_ID%TYPE;
   VNOM_PROV PROVEEDOR.NOMBRE%TYPE;
   VFECHA ORDENCOMPRA.FECHA%TYPE;
   VESTADO ORDENCOMPRA.ESTADO%TYPE;
   VCOUNT NUMBER := 0;
BEGIN
   T_ORDENES_POR_PROVEEDOR(DATOS,PPROVEEDOR_ID);
   LOOP
      FETCH DATOS INTO VORDEN,VPROV,VNOM_PROV,VFECHA,VESTADO;
      EXIT WHEN DATOS%NOTFOUND;
      DBMS_OUTPUT.PUT_LINE('OC: '||VORDEN||
                           ' PROVEEDOR: '||VPROV||' - '||VNOM_PROV||
                           ' FECHA: '||TO_CHAR(VFECHA,'DD/MM/YYYY')||
                           ' ESTADO: '||VESTADO);
      VCOUNT := VCOUNT + 1;
   END LOOP;
   DBMS_OUTPUT.PUT_LINE('TOTAL OC DEL PROVEEDOR '||PPROVEEDOR_ID||' = '||VCOUNT);
   CLOSE DATOS;
END;
/

--2)
--ABRE
CREATE OR REPLACE PROCEDURE T_ORDENES_POR_ESTADO(
CSDATOS OUT SYS_REFCURSOR,
PESTADO IN ORDENCOMPRA.ESTADO%TYPE
)
AS
BEGIN
   OPEN CSDATOS FOR
      SELECT O.ORDEN_COMPRA_ID,
             O.PROVEEDOR_ID,
             P.NOMBRE AS NOMBRE_PROVEEDOR,
             O.FECHA,
             O.ESTADO
      FROM ORDENCOMPRA O
      JOIN PROVEEDOR P ON P.PROVEEDOR_ID=O.PROVEEDOR_ID
      WHERE UPPER(O.ESTADO)=UPPER(PESTADO)
      ORDER BY O.FECHA DESC;
END;
/

--LLAMA
CREATE OR REPLACE PROCEDURE CALL_T_ORDENES_POR_ESTADO(
PESTADO IN ORDENCOMPRA.ESTADO%TYPE
)
AS
   DATOS SYS_REFCURSOR;
   VORDEN ORDENCOMPRA.ORDEN_COMPRA_ID%TYPE;
   VPROV PROVEEDOR.PROVEEDOR_ID%TYPE;
   VNOM_PROV PROVEEDOR.NOMBRE%TYPE;
   VFECHA ORDENCOMPRA.FECHA%TYPE;
   VESTADO ORDENCOMPRA.ESTADO%TYPE;
   VCOUNT NUMBER := 0;
BEGIN
   T_ORDENES_POR_ESTADO(DATOS,PESTADO);
   LOOP
      FETCH DATOS INTO VORDEN,VPROV,VNOM_PROV,VFECHA,VESTADO;
      EXIT WHEN DATOS%NOTFOUND;
      DBMS_OUTPUT.PUT_LINE('OC: '||VORDEN||
                           ' PROVEEDOR: '||VPROV||' - '||VNOM_PROV||
                           ' FECHA: '||TO_CHAR(VFECHA,'DD/MM/YYYY')||
                           ' ESTADO: '||VESTADO);
      VCOUNT := VCOUNT + 1;
   END LOOP;
   DBMS_OUTPUT.PUT_LINE('TOTAL OC EN ESTADO '||PESTADO||' = '||VCOUNT);
   CLOSE DATOS;
END;
/

--3)
--ABRE
CREATE OR REPLACE PROCEDURE T_DETALLE_OC_POR_PROVEEDOR(
CSDATOS OUT SYS_REFCURSOR,
PPROVEEDOR_ID IN PROVEEDOR.PROVEEDOR_ID%TYPE
)
AS
BEGIN
   OPEN CSDATOS FOR
      SELECT D.DETALLE_ORDEN_ID,
             O.ORDEN_COMPRA_ID,
             PR.PROVEEDOR_ID,
             PR.NOMBRE AS NOMBRE_PROVEEDOR,
             D.PRODUCTO_ID,
             P.NOMBRE AS NOMBRE_PRODUCTO,
             D.CANTIDAD
      FROM DETALLEORDEN D
      JOIN ORDENCOMPRA O ON O.ORDEN_COMPRA_ID=D.ORDEN_COMPRA_ID
      JOIN PROVEEDOR PR ON PR.PROVEEDOR_ID=O.PROVEEDOR_ID
      JOIN PRODUCTO P ON P.PRODUCTO_ID=D.PRODUCTO_ID
      WHERE PR.PROVEEDOR_ID=PPROVEEDOR_ID
      ORDER BY D.DETALLE_ORDEN_ID;
END;
/
--LLAMA
CREATE OR REPLACE PROCEDURE CALL_T_DETALLE_OC_POR_PROVEEDOR(
PPROVEEDOR_ID IN PROVEEDOR.PROVEEDOR_ID%TYPE
)
AS
   DATOS SYS_REFCURSOR;
   VDET DETALLEORDEN.DETALLE_ORDEN_ID%TYPE;
   VORDEN ORDENCOMPRA.ORDEN_COMPRA_ID%TYPE;
   VPROV PROVEEDOR.PROVEEDOR_ID%TYPE;
   VNOM_PROV PROVEEDOR.NOMBRE%TYPE;
   VPROD PRODUCTO.PRODUCTO_ID%TYPE;
   VNOM_PROD PRODUCTO.NOMBRE%TYPE;
   VCANT DETALLEORDEN.CANTIDAD%TYPE;
   VCOUNT NUMBER := 0;
BEGIN
   T_DETALLE_OC_POR_PROVEEDOR(DATOS,PPROVEEDOR_ID);
   LOOP
      FETCH DATOS INTO VDET,VORDEN,VPROV,VNOM_PROV,VPROD,VNOM_PROD,VCANT;
      EXIT WHEN DATOS%NOTFOUND;
      DBMS_OUTPUT.PUT_LINE('DET: '||VDET||
                           ' OC: '||VORDEN||
                           ' PROV: '||VPROV||' - '||VNOM_PROV||
                           ' PROD: '||VPROD||' - '||VNOM_PROD||
                           ' CANT: '||VCANT);
      VCOUNT := VCOUNT + 1;
   END LOOP;
   DBMS_OUTPUT.PUT_LINE('TOTAL DETALLES DE OC DEL PROVEEDOR '||PPROVEEDOR_ID||' = '||VCOUNT);
   CLOSE DATOS;
END;
/

--4)
CREATE OR REPLACE PROCEDURE SP_SQLDN_CURSOR_OC
AS
   VORDEN  ORDENCOMPRA.ORDEN_COMPRA_ID%TYPE;
   VPROV   ORDENCOMPRA.PROVEEDOR_ID%TYPE;
   VFECHA  ORDENCOMPRA.FECHA%TYPE;
   VESTADO ORDENCOMPRA.ESTADO%TYPE;
   VSQL    VARCHAR2(600);
   TYPE CUR IS REF CURSOR;
   CDATOS  CUR;
BEGIN
   VSQL := 'SELECT ORDEN_COMPRA_ID,PROVEEDOR_ID,FECHA,ESTADO
            FROM ORDENCOMPRA
            ORDER BY FECHA DESC';

   OPEN CDATOS FOR VSQL;

   LOOP
      FETCH CDATOS INTO VORDEN,VPROV,VFECHA,VESTADO;
      EXIT WHEN CDATOS%NOTFOUND;
      DBMS_OUTPUT.PUT_LINE(
         'OC: '||VORDEN||
         ' PROV: '||VPROV||
         ' FECHA: '||TO_CHAR(VFECHA,'DD/MM/YYYY')||
         ' ESTADO: '||VESTADO
      );
   END LOOP;

   CLOSE CDATOS;
END;
/



--PAQUETE
CREATE OR REPLACE PACKAGE pkg_compras_rep AS
    PROCEDURE sp_reporte_oc_por_proveedor (
        p_proveedor_id IN proveedor.proveedor_id%TYPE
    );

    PROCEDURE sp_reporte_oc_por_estado (
        p_estado IN ordencompra.estado%TYPE
    );

    PROCEDURE sp_reporte_detalle_oc_por_proveedor (
        p_proveedor_id IN proveedor.proveedor_id%TYPE
    );

    PROCEDURE sp_reporte_oc_sqldn;

END pkg_compras_rep;
/

--CUERPO
CREATE OR REPLACE PACKAGE BODY pkg_compras_rep AS

    PROCEDURE sp_reporte_oc_por_proveedor (
        p_proveedor_id IN proveedor.proveedor_id%TYPE
    ) AS
    BEGIN
        call_t_ordenes_por_proveedor(p_proveedor_id);
    END sp_reporte_oc_por_proveedor;

    PROCEDURE sp_reporte_oc_por_estado (
        p_estado IN ordencompra.estado%TYPE
    ) AS
    BEGIN
        call_t_ordenes_por_estado(p_estado);
    END sp_reporte_oc_por_estado;

    PROCEDURE sp_reporte_detalle_oc_por_proveedor (
        p_proveedor_id IN proveedor.proveedor_id%TYPE
    ) AS
    BEGIN
        call_t_detalle_oc_por_proveedor(p_proveedor_id);
    END sp_reporte_detalle_oc_por_proveedor;

    PROCEDURE sp_reporte_oc_sqldn AS
    BEGIN
        sp_sqldn_cursor_oc;
    END sp_reporte_oc_sqldn;

END pkg_compras_rep;
/


SET SERVEROUTPUT ON;


EXEC pkg_compras_rep.sp_reporte_oc_por_proveedor(1);
EXEC pkg_compras_rep.sp_reporte_oc_por_estado('RECIBIDA');
EXEC pkg_compras_rep.sp_reporte_detalle_oc_por_proveedor(1);
EXEC pkg_compras_rep.sp_reporte_oc_sqldn;




