--1)
--ABRIR
CREATE OR REPLACE PROCEDURE T_CLIENTES_CON_PEDIDOS(
CSDATOS OUT SYS_REFCURSOR
)
AS
BEGIN
   OPEN CSDATOS FOR
      SELECT C.CLIENTE_ID,
             C.NOMBRE,
             COUNT(P.PEDIDO_ID) AS TOTAL_PEDIDOS
      FROM CLIENTE C
      JOIN PEDIDO P ON P.CLIENTE_ID=C.CLIENTE_ID
      GROUP BY C.CLIENTE_ID,C.NOMBRE
      ORDER BY TOTAL_PEDIDOS DESC;
END;
/

--LLAMAR
CREATE OR REPLACE PROCEDURE CALL_T_CLIENTES_CON_PEDIDOS
AS
   DATOS SYS_REFCURSOR;
   VID CLIENTE.CLIENTE_ID%TYPE;
   VNOM CLIENTE.NOMBRE%TYPE;
   VTOTAL NUMBER;
BEGIN
   T_CLIENTES_CON_PEDIDOS(DATOS);
   LOOP
      FETCH DATOS INTO VID,VNOM,VTOTAL;
      EXIT WHEN DATOS%NOTFOUND;
      DBMS_OUTPUT.PUT_LINE('CLIENTE: '||VID||' '||VNOM||' - PEDIDOS: '||VTOTAL);
   END LOOP;
   CLOSE DATOS;
END;
/

--2)
--ABRIR
CREATE OR REPLACE PROCEDURE T_CLIENTES_SIN_PEDIDOS(
CSDATOS OUT SYS_REFCURSOR
)
AS
BEGIN
   OPEN CSDATOS FOR
      SELECT C.CLIENTE_ID,
             C.NOMBRE
      FROM CLIENTE C
      WHERE NOT EXISTS (
         SELECT 1 FROM PEDIDO P
         WHERE P.CLIENTE_ID=C.CLIENTE_ID
      )
      ORDER BY C.NOMBRE;
END;
/

--CONSUME
CREATE OR REPLACE PROCEDURE CALL_T_CLIENTES_SIN_PEDIDOS
AS
   DATOS SYS_REFCURSOR;
   VID CLIENTE.CLIENTE_ID%TYPE;
   VNOM CLIENTE.NOMBRE%TYPE;
BEGIN
   T_CLIENTES_SIN_PEDIDOS(DATOS);
   LOOP
      FETCH DATOS INTO VID,VNOM;
      EXIT WHEN DATOS%NOTFOUND;
      DBMS_OUTPUT.PUT_LINE('CLIENTE SIN PEDIDOS: '||VID||' '||VNOM);
   END LOOP;
   CLOSE DATOS;
END;
/

--3)
CREATE OR REPLACE PROCEDURE SP_SQLDN_CURSOR_CLIENTE
AS
   VID NUMBER;
   VNOM VARCHAR2(150);
   VCORREO VARCHAR2(150);
   VSQL VARCHAR2(600);
   TYPE CUR IS REF CURSOR;
   CDATOS CUR;
BEGIN
   VSQL := 'SELECT CLIENTE_ID,NOMBRE,CORREO FROM CLIENTE';

   OPEN CDATOS FOR VSQL;

   LOOP
      FETCH CDATOS INTO VID,VNOM,VCORREO;
      EXIT WHEN CDATOS%NOTFOUND;
      DBMS_OUTPUT.PUT_LINE('CLIENTE: '||VID||' '||VNOM||' CORREO: '||VCORREO);
   END LOOP;

   CLOSE CDATOS;
END;
/

--PAQUETE
CREATE OR REPLACE PACKAGE pkg_cliente_rep AS
    PROCEDURE sp_reporte_clientes_con_pedidos;

    PROCEDURE sp_reporte_clientes_sin_pedidos;

    PROCEDURE sp_reporte_clientes_sqldn;

END pkg_cliente_rep;
/

--CUERPO
CREATE OR REPLACE PACKAGE BODY pkg_cliente_rep AS

    PROCEDURE sp_reporte_clientes_con_pedidos AS
    BEGIN
        call_t_clientes_con_pedidos;
    END sp_reporte_clientes_con_pedidos;

    PROCEDURE sp_reporte_clientes_sin_pedidos AS
    BEGIN
        call_t_clientes_sin_pedidos;
    END sp_reporte_clientes_sin_pedidos;

    PROCEDURE sp_reporte_clientes_sqldn AS
    BEGIN
        sp_sqldn_cursor_cliente;
    END sp_reporte_clientes_sqldn;

END pkg_cliente_rep;
/


SET SERVEROUTPUT ON;


-- 
EXEC PKG_CLIENTE_REP.SP_REPORTE_CLIENTES_CON_PEDIDOS;
EXEC PKG_CLIENTE_REP.SP_REPORTE_CLIENTES_SIN_PEDIDOS;
EXEC PKG_CLIENTE_REP.sp_reporte_clientes_sqldn;

