--1)
CREATE OR REPLACE VIEW VW_PRODUCTOS_CON_STOCK AS
SELECT P.PRODUCTO_ID,
       P.NOMBRE,
       P.CATEGORIA,
       P.DESCRIPCION,
       P.PRECIO,
       NVL(I.CANTIDAD_ACTUAL,0) AS CANTIDAD_ACTUAL
FROM PRODUCTO P
LEFT JOIN INVENTARIO I
   ON I.PRODUCTO_ID = P.PRODUCTO_ID;

--2
CREATE OR REPLACE VIEW VW_PEDIDOS_DETALLADOS AS
SELECT P.PEDIDO_ID,
       C.CLIENTE_ID,
       C.NOMBRE AS NOMBRE_CLIENTE,
       P.FECHA,
       P.ESTADO,
       D.DETALLE_PEDIDO_ID,
       PR.PRODUCTO_ID,
       PR.NOMBRE AS NOMBRE_PRODUCTO,
       D.CANTIDAD,
       D.SUBTOTAL
FROM PEDIDO P
JOIN CLIENTE C
   ON C.CLIENTE_ID = P.CLIENTE_ID
JOIN DETALLEPEDIDO D
   ON D.PEDIDO_ID = P.PEDIDO_ID
JOIN PRODUCTO PR
   ON PR.PRODUCTO_ID = D.PRODUCTO_ID;

--3
CREATE OR REPLACE VIEW VW_CLIENTES_CON_PEDIDOS AS
SELECT C.CLIENTE_ID,
       C.NOMBRE,
       C.CORREO,
       COUNT(P.PEDIDO_ID) AS TOTAL_PEDIDOS
FROM CLIENTE C
JOIN PEDIDO P
   ON P.CLIENTE_ID = C.CLIENTE_ID
GROUP BY C.CLIENTE_ID,
         C.NOMBRE,
         C.CORREO;

--4
CREATE OR REPLACE VIEW VW_CLIENTES_SIN_PEDIDOS AS
SELECT C.CLIENTE_ID,
       C.NOMBRE,
       C.CORREO,
       C.TELEFONO
FROM CLIENTE C
WHERE NOT EXISTS (
   SELECT 1
   FROM PEDIDO P
   WHERE P.CLIENTE_ID = C.CLIENTE_ID
);

--5
CREATE OR REPLACE VIEW VW_RECLAMOS_CLIENTE AS
SELECT R.RECLAMO_ID,
       A.ATENCION_ID,
       C.CLIENTE_ID,
       C.NOMBRE AS NOMBRE_CLIENTE,
       R.DETALLE_PEDIDO_ID,
       R.TIPO_RECLAMO,
       R.DESCRIPCION,
       R.ESTADO
FROM RECLAMO R
JOIN ATENCIONCLIENTE A
   ON A.ATENCION_ID = R.ATENCION_ID
JOIN CLIENTE C
   ON C.CLIENTE_ID = A.CLIENTE_ID;

--6
CREATE OR REPLACE VIEW VW_DEVOLUCIONES_DETALLADAS AS
SELECT D.DEVOLUCION_ID,
       D.DETALLE_PEDIDO_ID,
       D.RECLAMO_ID,
       R.TIPO_RECLAMO,
       D.MOTIVO,
       D.ESTADO AS ESTADO_DEVOLUCION,
       C.CLIENTE_ID,
       C.NOMBRE AS NOMBRE_CLIENTE,
       PR.PRODUCTO_ID,
       PR.NOMBRE AS NOMBRE_PRODUCTO
FROM DEVOLUCION D
JOIN RECLAMO R
   ON R.RECLAMO_ID = D.RECLAMO_ID
JOIN ATENCIONCLIENTE A
   ON A.ATENCION_ID = R.ATENCION_ID
JOIN CLIENTE C
   ON C.CLIENTE_ID = A.CLIENTE_ID
JOIN DETALLEPEDIDO DP
   ON DP.DETALLE_PEDIDO_ID = D.DETALLE_PEDIDO_ID
JOIN PRODUCTO PR
   ON PR.PRODUCTO_ID = DP.PRODUCTO_ID;

--7
CREATE OR REPLACE VIEW VW_OC_DETALLADA AS
SELECT O.ORDEN_COMPRA_ID,
       O.FECHA,
       O.ESTADO,
       PRV.PROVEEDOR_ID,
       PRV.NOMBRE AS NOMBRE_PROVEEDOR,
       D.DETALLE_ORDEN_ID,
       P.PRODUCTO_ID,
       P.NOMBRE AS NOMBRE_PRODUCTO,
       D.CANTIDAD
FROM ORDENCOMPRA O
JOIN PROVEEDOR PRV
   ON PRV.PROVEEDOR_ID = O.PROVEEDOR_ID
JOIN DETALLEORDEN D
   ON D.ORDEN_COMPRA_ID = O.ORDEN_COMPRA_ID
JOIN PRODUCTO P
   ON P.PRODUCTO_ID = D.PRODUCTO_ID;

--8
CREATE OR REPLACE VIEW VW_OC_RESUMEN_PROVEEDOR AS
SELECT PRV.PROVEEDOR_ID,
       PRV.NOMBRE AS NOMBRE_PROVEEDOR,
       COUNT(O.ORDEN_COMPRA_ID) AS TOTAL_ORDENES
FROM PROVEEDOR PRV
LEFT JOIN ORDENCOMPRA O
   ON O.PROVEEDOR_ID = PRV.PROVEEDOR_ID
GROUP BY PRV.PROVEEDOR_ID,
         PRV.NOMBRE;

--9
CREATE OR REPLACE VIEW VW_ESTADO_PEDIDOS AS
SELECT P.ESTADO,
       COUNT(P.PEDIDO_ID) AS TOTAL_PEDIDOS
FROM PEDIDO P
GROUP BY P.ESTADO;

--10
CREATE OR REPLACE VIEW VW_TOP_PRODUCTOS_VENDIDOS AS
SELECT PR.PRODUCTO_ID,
       PR.NOMBRE AS NOMBRE_PRODUCTO,
       SUM(D.CANTIDAD) AS TOTAL_VENDIDO
FROM PRODUCTO PR
JOIN DETALLEPEDIDO D
   ON D.PRODUCTO_ID = PR.PRODUCTO_ID
GROUP BY PR.PRODUCTO_ID,
         PR.NOMBRE;


SELECT * FROM VW_PRODUCTOS_CON_STOCK ORDER BY PRECIO DESC;

SELECT * FROM VW_PEDIDOS_DETALLADOS;

SELECT * FROM VW_CLIENTES_CON_PEDIDOS;

SELECT * FROM VW_CLIENTES_SIN_PEDIDOS;

SELECT * FROM VW_RECLAMOS_CLIENTE;

SELECT * FROM VW_DEVOLUCIONES_DETALLADAS;

SELECT * FROM VW_OC_DETALLADA;

SELECT * FROM VW_OC_RESUMEN_PROVEEDOR;

SELECT * FROM VW_ESTADO_PEDIDOS;

SELECT * FROM VW_TOP_PRODUCTOS_VENDIDOS;

