-- Producto
CREATE TABLE Producto (
    producto_ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nombre      VARCHAR2(50 CHAR)   NOT NULL,
    categoria   VARCHAR2(30 CHAR)   NOT NULL,
    descripcion VARCHAR2(255 CHAR)  NOT NULL,
    precio      NUMBER(10,2)        NOT NULL
);


-- Inventario
CREATE TABLE Inventario (
    producto_ID     NUMBER      PRIMARY KEY,
    cantidad_actual NUMBER      NOT NULL,
    CONSTRAINT fk_inv_producto
        FOREIGN KEY (producto_ID) REFERENCES Producto(producto_ID)
);

-- Cliente
CREATE TABLE Cliente (
    cliente_ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nombre     VARCHAR2(100 CHAR) NOT NULL,
    correo     VARCHAR2(100 CHAR) NOT NULL,
    telefono   VARCHAR2(20 CHAR)  NOT NULL,
    direccion  VARCHAR2(255 CHAR) NOT NULL
);

-- Pedido
CREATE TABLE Pedido (
    pedido_ID  NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    cliente_ID NUMBER        NOT NULL,
    fecha      DATE          NOT NULL,
    estado     VARCHAR2(30 CHAR) NOT NULL,
    CONSTRAINT fk_pedido_cliente
        FOREIGN KEY (cliente_ID) REFERENCES Cliente(cliente_ID)
);

-- DetallePedido
CREATE TABLE DetallePedido (
    detalle_pedido_ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    pedido_ID         NUMBER       NOT NULL,
    producto_ID       NUMBER       NOT NULL,
    cantidad          NUMBER       NOT NULL,
    subtotal          NUMBER(10,2),
    CONSTRAINT fk_det_ped_pedido
        FOREIGN KEY (pedido_ID) REFERENCES Pedido(pedido_ID),
    CONSTRAINT fk_det_ped_producto
        FOREIGN KEY (producto_ID) REFERENCES Producto(producto_ID)
);

-- AtencionCliente
CREATE TABLE AtencionCliente (
    atencion_ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    cliente_ID  NUMBER        NOT NULL,
    pedido_ID   NUMBER,
    tipo        VARCHAR2(50 CHAR)  NOT NULL,
    descripcion VARCHAR2(255 CHAR) NOT NULL,
    fecha       DATE          NOT NULL,
    estado      VARCHAR2(30 CHAR)  NOT NULL,
    CONSTRAINT fk_atc_cliente
        FOREIGN KEY (cliente_ID) REFERENCES Cliente(cliente_ID),
    CONSTRAINT fk_atc_pedido
        FOREIGN KEY (pedido_ID)  REFERENCES Pedido(pedido_ID)
);

-- Reclamo
CREATE TABLE Reclamo (
    reclamo_ID         NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    atencion_ID        NUMBER       NOT NULL,
    detalle_pedido_ID  NUMBER       NOT NULL,
    tipo_reclamo       VARCHAR2(50 CHAR)  NOT NULL,
    descripcion        VARCHAR2(255 CHAR) NOT NULL,
    estado             VARCHAR2(30 CHAR)  NOT NULL,
    CONSTRAINT fk_reclamo_atencion
        FOREIGN KEY (atencion_ID)       REFERENCES AtencionCliente(atencion_ID),
    CONSTRAINT fk_reclamo_detalle
        FOREIGN KEY (detalle_pedido_ID) REFERENCES DetallePedido(detalle_pedido_ID)
);

-- Devolucion
CREATE TABLE Devolucion (
    devolucion_ID     NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    detalle_pedido_ID NUMBER       NOT NULL,
    reclamo_ID        NUMBER       NOT NULL,
    motivo            VARCHAR2(255 CHAR) NOT NULL,
    estado            VARCHAR2(30 CHAR)  NOT NULL,
    CONSTRAINT fk_dev_detalle
        FOREIGN KEY (detalle_pedido_ID) REFERENCES DetallePedido(detalle_pedido_ID),
    CONSTRAINT fk_dev_reclamo
        FOREIGN KEY (reclamo_ID)        REFERENCES Reclamo(reclamo_ID)
);

-- Proveedor
CREATE TABLE Proveedor (
    proveedor_ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nombre       VARCHAR2(100 CHAR) NOT NULL,
    telefono     VARCHAR2(20 CHAR)  NOT NULL,
    correo       VARCHAR2(100 CHAR) NOT NULL
);

-- ProductoProveedor 
CREATE TABLE ProductoProveedor (
    proveedor_ID NUMBER NOT NULL,
    producto_ID  NUMBER NOT NULL,
    CONSTRAINT pk_prod_prov PRIMARY KEY (proveedor_ID, producto_ID),
    CONSTRAINT fk_pp_proveedor FOREIGN KEY (proveedor_ID) REFERENCES Proveedor(proveedor_ID),
    CONSTRAINT fk_pp_producto  FOREIGN KEY (producto_ID)  REFERENCES Producto(producto_ID)
);

-- OrdenCompra
CREATE TABLE OrdenCompra (
    orden_compra_ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    proveedor_ID    NUMBER       NOT NULL,
    fecha           DATE         NOT NULL,
    estado          VARCHAR2(30 CHAR) NOT NULL,
    CONSTRAINT fk_oc_proveedor
        FOREIGN KEY (proveedor_ID) REFERENCES Proveedor(proveedor_ID)
);

-- DetalleOrden
CREATE TABLE DetalleOrden (
    detalle_orden_ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    orden_compra_ID  NUMBER       NOT NULL,
    producto_ID      NUMBER       NOT NULL,
    cantidad         NUMBER       NOT NULL,
    CONSTRAINT fk_do_oc       FOREIGN KEY (orden_compra_ID) REFERENCES OrdenCompra(orden_compra_ID),
    CONSTRAINT fk_do_producto FOREIGN KEY (producto_ID)     REFERENCES Producto(producto_ID)
);


CREATE TABLE Usuario (
    usuario_ID      NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre_usuario  VARCHAR2(60)   NOT NULL,
    contraseña      VARCHAR2(255)  NOT NULL,
    rol             VARCHAR2(30)   NOT NULL,
    estado          VARCHAR2(20)   NOT NULL
)
