----------------------VERIFICACIÓN INICIAL---------------------------------

--VERIFICAR EL CONTENEDOR
show con_name;

--VERIFICAR EL USUARIO
show user;

--CAMBIAR EL CONTENEDOR
ALTER SESSION SET CONTAINER = XEPDB1;

--VERIFICAR DONDE GUARDAR LOS TABLESPACES(RUTA)

SELECT tablespace_name, file_name FROM dba_data_files;

---------------------------- DESARROLLO ------------------------------------

--Tablespaces
CREATE TABLESPACE ts_proyectoSC504          --[CAMBIAR RUTA ACÁ]
    DATAFILE 'C:\APP\PC\PRODUCT\21C\ORADATA\XE\XEPDB1\ts_proyectoSC504.dbf' SIZE 50M
    AUTOEXTEND ON NEXT 10M MAXSIZE 500M;

CREATE TEMPORARY TABLESPACE ts_temp_proyectoSC504
  TEMPFILE 'C:\APP\PC\PRODUCT\21C\ORADATA\XE\XEPDB1\ts_temp_proyectoSC504.tmp'
  SIZE 50M AUTOEXTEND ON NEXT 10M MAXSIZE 500M;
    

--User

CREATE USER DESARROLLADOR IDENTIFIED BY "admin123"
  DEFAULT TABLESPACE ts_proyectoSC504
  TEMPORARY TABLESPACE ts_temp_proyectoSC504
  QUOTA UNLIMITED ON ts_proyectoSC504;
  
--Rol

CREATE ROLE ROL_DESARROLLADOR;

--Permisos

GRANT 
    CREATE SESSION,
    CREATE TABLE,
    CREATE VIEW,
    CREATE SEQUENCE,
    CREATE PROCEDURE,
    CREATE SYNONYM,
    ALTER SESSION,
    CREATE TRIGGER
TO ROL_DESARROLLADOR;

--Asiganación de rol

GRANT ROL_DESARROLLADOR TO DESARROLLADOR;

