--1 ABRIR
CREATE OR REPLACE PROCEDURE T_PROD_POR_CATEGORIA(
CSDATOS OUT SYS_REFCURSOR,
PCATEGORIA IN PRODUCTO.CATEGORIA%TYPE
)
AS
BEGIN
   OPEN CSDATOS FOR
      SELECT P.PRODUCTO_ID,
             P.NOMBRE,
             P.CATEGORIA,
             P.DESCRIPCION,
             P.PRECIO
      FROM PRODUCTO P
      WHERE UPPER(P.CATEGORIA)=UPPER(PCATEGORIA)
      ORDER BY P.NOMBRE;
END;
/

--2 CURSOR LLAMADA
CREATE OR REPLACE PROCEDURE CALL_T_PROD_POR_CATEGORIA(
PCATEGORIA IN PRODUCTO.CATEGORIA%TYPE
)
AS
   DATOS SYS_REFCURSOR;
   VID PRODUCTO.PRODUCTO_ID%TYPE;
   VNOM PRODUCTO.NOMBRE%TYPE;
   VCATEG PRODUCTO.CATEGORIA%TYPE;
   VDESC PRODUCTO.DESCRIPCION%TYPE;
   VPRECIO PRODUCTO.PRECIO%TYPE;
   VSUM NUMBER := 0;
BEGIN
   T_PROD_POR_CATEGORIA(DATOS,PCATEGORIA);
   LOOP
      FETCH DATOS INTO VID,VNOM,VCATEG,VDESC,VPRECIO;
      EXIT WHEN DATOS%NOTFOUND;
      DBMS_OUTPUT.PUT_LINE('- PRODUCTO: '||VID||' '||VNOM||
                           ' CAT: '||VCATEG||
                           ' PRECIO: '||VPRECIO);
      VSUM := VSUM + VPRECIO;
   END LOOP;
   DBMS_OUTPUT.PUT_LINE('SUMA TOTAL PRECIO CATEGORIA '||PCATEGORIA||' = '||VSUM);
   CLOSE DATOS;
END;
/

--3 CURSOR DINAMICO 

CREATE OR REPLACE PROCEDURE SP_SQLDN_CURSOR_PROD
AS
   VID NUMBER;
   VNOM VARCHAR2(156);
   VCATEG VARCHAR2(50);
   VSQL VARCHAR2(600);
   TYPE CUR IS REF CURSOR;
   CDATOS CUR;
BEGIN
   VSQL := 'SELECT PRODUCTO_ID, NOMBRE, CATEGORIA
            FROM PRODUCTO
            WHERE PRECIO > 0';

   OPEN CDATOS FOR VSQL;

   LOOP
      FETCH CDATOS INTO VID,VNOM,VCATEG;
      EXIT WHEN CDATOS%NOTFOUND;
      DBMS_OUTPUT.PUT_LINE('PROD: '||VID||' '||VNOM||' CAT: '||VCATEG);
   END LOOP;

   CLOSE CDATOS;
END;
/

--DECLARACIÓN PAQUETE
CREATE OR REPLACE PACKAGE PKG_PRODUCTO_REP AS

PROCEDURE SP_REPORTE_PROD_POR_CATEGORIA(
p_categoria IN PRODUCTO.CATEGORIA%TYPE
);

PROCEDURE SP_REPORTE_PROD_SQLDN;

END PKG_PRODUCTO_REP;
/

--CUERPO
CREATE OR REPLACE PACKAGE BODY PKG_PRODUCTO_REP AS

PROCEDURE SP_REPORTE_PROD_POR_CATEGORIA(
p_categoria IN PRODUCTO.CATEGORIA%TYPE
) AS
BEGIN
   CALL_T_PROD_POR_CATEGORIA(p_categoria);
END SP_REPORTE_PROD_POR_CATEGORIA;


PROCEDURE SP_REPORTE_PROD_SQLDN
AS
BEGIN
   SP_SQLDN_CURSOR_PROD;
END SP_REPORTE_PROD_SQLDN;

END PKG_PRODUCTO_REP;
/


SET SERVEROUTPUT ON;

EXEC PKG_PRODUCTO_REP.SP_REPORTE_PROD_POR_CATEGORIA('Tecnología');

EXEC PKG_PRODUCTO_REP.SP_REPORTE_PROD_SQLDN;

