--1)
--ABRE
CREATE OR REPLACE PROCEDURE T_RECLAMOS_POR_CLIENTE(
CSDATOS OUT SYS_REFCURSOR,
PCLIENTE_ID IN CLIENTE.CLIENTE_ID%TYPE
)
AS
BEGIN
   OPEN CSDATOS FOR
      SELECT R.RECLAMO_ID,
             A.ATENCION_ID,
             C.CLIENTE_ID,
             C.NOMBRE AS NOMBRE_CLIENTE,
             R.DETALLE_PEDIDO_ID,
             R.TIPO_RECLAMO,
             R.DESCRIPCION,
             R.ESTADO
      FROM RECLAMO R
      JOIN ATENCIONCLIENTE A ON A.ATENCION_ID=R.ATENCION_ID
      JOIN CLIENTE C ON C.CLIENTE_ID=A.CLIENTE_ID
      WHERE C.CLIENTE_ID=PCLIENTE_ID
      ORDER BY R.RECLAMO_ID;
END;
/


--CONSUME
CREATE OR REPLACE PROCEDURE CALL_T_RECLAMOS_POR_CLIENTE(
PCLIENTE_ID IN CLIENTE.CLIENTE_ID%TYPE
)
AS
   DATOS SYS_REFCURSOR;
   VRECLAMO RECLAMO.RECLAMO_ID%TYPE;
   VATENCION ATENCIONCLIENTE.ATENCION_ID%TYPE;
   VCLIENTE CLIENTE.CLIENTE_ID%TYPE;
   VNOM_CLIENTE CLIENTE.NOMBRE%TYPE;
   VDETALLE RECLAMO.DETALLE_PEDIDO_ID%TYPE;
   VTIPO RECLAMO.TIPO_RECLAMO%TYPE;
   VDESC RECLAMO.DESCRIPCION%TYPE;
   VESTADO RECLAMO.ESTADO%TYPE;
   VCOUNT NUMBER:=0;
BEGIN
   T_RECLAMOS_POR_CLIENTE(DATOS,PCLIENTE_ID);
   LOOP
      FETCH DATOS INTO VRECLAMO,VATENCION,VCLIENTE,VNOM_CLIENTE,
                       VDETALLE,VTIPO,VDESC,VESTADO;
      EXIT WHEN DATOS%NOTFOUND;
      DBMS_OUTPUT.PUT_LINE('RECLAMO: '||VRECLAMO||
                           ' CLIENTE: '||VCLIENTE||' - '||VNOM_CLIENTE||
                           ' TIPO: '||VTIPO||
                           ' ESTADO: '||VESTADO);
      VCOUNT:=VCOUNT+1;
   END LOOP;
   DBMS_OUTPUT.PUT_LINE('TOTAL RECLAMOS DEL CLIENTE '||PCLIENTE_ID||' = '||VCOUNT);
   CLOSE DATOS;
END;
/

--2)
--ABRE
CREATE OR REPLACE PROCEDURE T_DEVOLUCIONES_POR_ESTADO(
CSDATOS OUT SYS_REFCURSOR,
PESTADO IN DEVOLUCION.ESTADO%TYPE
)
AS
BEGIN
   OPEN CSDATOS FOR
      SELECT D.DEVOLUCION_ID,
             D.DETALLE_PEDIDO_ID,
             D.RECLAMO_ID,
             R.TIPO_RECLAMO,
             D.MOTIVO,
             D.ESTADO,
             C.CLIENTE_ID,
             C.NOMBRE AS NOMBRE_CLIENTE
      FROM DEVOLUCION D
      JOIN RECLAMO R ON R.RECLAMO_ID=D.RECLAMO_ID
      JOIN ATENCIONCLIENTE A ON A.ATENCION_ID=R.ATENCION_ID
      JOIN CLIENTE C ON C.CLIENTE_ID=A.CLIENTE_ID
      WHERE UPPER(D.ESTADO)=UPPER(PESTADO)
      ORDER BY D.DEVOLUCION_ID;
END;
/


--CONSUME
CREATE OR REPLACE PROCEDURE CALL_T_DEVOLUCIONES_POR_ESTADO(
PESTADO IN DEVOLUCION.ESTADO%TYPE
)
AS
   DATOS SYS_REFCURSOR;
   VDEV DEVOLUCION.DEVOLUCION_ID%TYPE;
   VDET DEVOLUCION.DETALLE_PEDIDO_ID%TYPE;
   VREC DEVOLUCION.RECLAMO_ID%TYPE;
   VTIPO RECLAMO.TIPO_RECLAMO%TYPE;
   VMOTIVO DEVOLUCION.MOTIVO%TYPE;
   VESTADO DEVOLUCION.ESTADO%TYPE;
   VCLIENTE CLIENTE.CLIENTE_ID%TYPE;
   VNOM_CLIENTE CLIENTE.NOMBRE%TYPE;
   VCOUNT NUMBER:=0;
BEGIN
   T_DEVOLUCIONES_POR_ESTADO(DATOS,PESTADO);
   LOOP
      FETCH DATOS INTO VDEV,VDET,VREC,VTIPO,VMOTIVO,VESTADO,
                       VCLIENTE,VNOM_CLIENTE;
      EXIT WHEN DATOS%NOTFOUND;
      DBMS_OUTPUT.PUT_LINE('DEVOLUCION: '||VDEV||
                           ' RECLAMO: '||VREC||
                           ' CLIENTE: '||VCLIENTE||' - '||VNOM_CLIENTE||
                           ' TIPO: '||VTIPO||
                           ' ESTADO: '||VESTADO);
      VCOUNT:=VCOUNT+1;
   END LOOP;
   DBMS_OUTPUT.PUT_LINE('TOTAL DEVOLUCIONES EN ESTADO '||PESTADO||' = '||VCOUNT);
   CLOSE DATOS;
END;
/

--3
CREATE OR REPLACE PROCEDURE SP_SQLDN_CURSOR_RECLAMO
AS
   VREC NUMBER;
   VATENCION NUMBER;
   VCLIENTE NUMBER;
   VNOM_CLIENTE VARCHAR2(150);
   VESTADO VARCHAR2(50);
   VSQL VARCHAR2(600);
   TYPE CUR IS REF CURSOR;
   CDATOS CUR;
BEGIN
   VSQL:='SELECT R.RECLAMO_ID,
                 A.ATENCION_ID,
                 C.CLIENTE_ID,
                 C.NOMBRE,
                 R.ESTADO
          FROM RECLAMO R
          JOIN ATENCIONCLIENTE A ON A.ATENCION_ID=R.ATENCION_ID
          JOIN CLIENTE C ON C.CLIENTE_ID=A.CLIENTE_ID
          ORDER BY R.RECLAMO_ID';

   OPEN CDATOS FOR VSQL;

   LOOP
      FETCH CDATOS INTO VREC,VATENCION,VCLIENTE,VNOM_CLIENTE,VESTADO;
      EXIT WHEN CDATOS%NOTFOUND;
      DBMS_OUTPUT.PUT_LINE('RECLAMO: '||VREC||
                           ' ATENCION: '||VATENCION||
                           ' CLIENTE: '||VCLIENTE||' - '||VNOM_CLIENTE||
                           ' ESTADO: '||VESTADO);
   END LOOP;

   CLOSE CDATOS;
END;
/


--PAQUETE
--DECLARA
CREATE OR REPLACE PACKAGE pkg_reclamos_rep AS
    PROCEDURE sp_reporte_reclamos_por_cliente (
        p_cliente_id IN cliente.cliente_id%TYPE
    );

    PROCEDURE sp_reporte_devoluciones_por_estado (
        p_estado IN devolucion.estado%TYPE
    );

    PROCEDURE sp_reporte_reclamos_sqldn;

END pkg_reclamos_rep;
/

--CUERPO
CREATE OR REPLACE PACKAGE BODY pkg_reclamos_rep AS

    PROCEDURE sp_reporte_reclamos_por_cliente (
        p_cliente_id IN cliente.cliente_id%TYPE
    ) AS
    BEGIN
        call_t_reclamos_por_cliente(p_cliente_id);
    END sp_reporte_reclamos_por_cliente;

    PROCEDURE sp_reporte_devoluciones_por_estado (
        p_estado IN devolucion.estado%TYPE
    ) AS
    BEGIN
        call_t_devoluciones_por_estado(p_estado);
    END sp_reporte_devoluciones_por_estado;

    PROCEDURE sp_reporte_reclamos_sqldn AS
    BEGIN
        sp_sqldn_cursor_reclamo;
    END sp_reporte_reclamos_sqldn;

END pkg_reclamos_rep;
/


SET SERVEROUTPUT ON;

EXEC PKG_RECLAMOS_REP.SP_REPORTE_RECLAMOS_POR_CLIENTE(1);
EXEC PKG_RECLAMOS_REP.SP_REPORTE_DEVOLUCIONES_POR_ESTADO('APROBADA');
EXEC PKG_RECLAMOS_REP.SP_REPORTE_RECLAMOS_SQLDN;

